### ISSUE TITLE
System Developer

### ISSUE THREAD

**Issue by m20uk** [DMU-CTEC2902/GoodMorning-Repo#3]
Push the master page of the project and modify the website pages.

**Comment by Abdullah5000** [comment]
During the reading week I've pushed the master branch and I am trying to modify the pages but I've got some errors. In addition, I've helped Abdullaziz to create the classes diagram and I've created the Use case diagrams
![use case manager](https://user-images.githubusercontent.com/46674952/53704170-31f53e00-3e12-11e9-8802-aa205e22d587.jpg)
![use case users](https://user-images.githubusercontent.com/46674952/53704171-31f53e00-3e12-11e9-9a03-345facd9631d.jpg)
